name: CI-build-main-branch
on:
  push:
    branches: [master]
  pull_request:
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: "deadbeef.flatpak"
        manifest-path: "music.deadbeef.player-master.json"
